---
#
# Ansible managed
#
repository:
  description: Install and configure ntp on your system.
  homepage: https://buluma.github.io/
  topics: ntp, ntpd, ntpdate, ansible, molecule, tox, playbook, hacktoberfest
