---
# handlers file for ntp

- name: Restart ntp
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool
    - ntp_state == "started"
